name: clean_architecture
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  provider: ^6.1.1
  url_launcher: ^6.2.4
  local_auth: ^2.1.8
  flutter_local_notifications: ^16.3.2
  flutter_dotenv: ^5.1.0
  web: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1

  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  change_app_package_name: ^1.1.0
  
flutter:
  uses-material-design: true
  assets:
  - .env
